version: '3'

services:
  backend:
    image: phonebook:demo
    ports:
      - "8080:8080"
    network_mode: bridge
    depends_on:
      - db
      - redis

  db:
    image: phonebook:db
    environment:
      MYSQL_ROOT_PASSWORD: mySuperSecretPassword
    ports:
      - "3306:3306"
    network_mode: bridge

  redis:
    image: phonebook:redis
    ports:
      - "6379:6379"
    network_mode: bridge