multipart:
  maxFileSize: 128000KB
  maxRequestSize: 128000KB

spring:
  profiles:
    active: jpa

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  ## Redis cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    ssl: false

flyway:
  baselineOnMigrate: true

## Facebook oauth2
security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://graph.facebook.com/me